ARG BASE_IMAGE=ghcr.io/cryptic-stack/octal-neko/nvidia-base:latest
FROM $BASE_IMAGE

COPY ./widevinecdm.sh /widevine.sh

#
# install octal chromium
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends software-properties-common; \
    #Ã‚Â chromium-browser from default repo needs snap to be installed
    # and nvidia base is ubuntu not debian
    add-apt-repository ppa:system76/pop; \
    apt-get update; \
    apt-get install -y --no-install-recommends xz-utils chromium openbox; \
    #
    # install widevine module
    CHROMIUM_DIR="/usr/lib/chromium"; \
    ./widevine.sh "${CHROMIUM_DIR}/WidevineCdm"; \
    rm -f /widevine.sh; \
    #
    # clean up
    apt-get --purge autoremove -y xz-utils; \
    apt-get clean -y; \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

#
# copy configuation files
COPY supervisord.nvidia.conf /etc/neko/supervisord/chromium.conf
COPY --chown=octal preferences.json /home/octal/.config/chromium/Default/Preferences
COPY policies.json /etc/chromium/policies/managed/policies.json
COPY openbox.xml /etc/neko/openbox.xml

